services:
  - type: web
    name: master-can-license-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    disk:
      name: master-can-data
      mountPath: /var/data
      sizeGB: 1
