services:
  - type: web
    name: master-can-licencas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_PATH
        value: /var/data/licencas.db
    disk:
      name: master-can-db
      mountPath: /var/data
      sizeGB: 1
